# Generated by Django 2.2.6 on 2019-10-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20191029_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='font_size',
            field=models.PositiveSmallIntegerField(default=12),
            preserve_default=False,
        ),
    ]
