# Generated by Django 2.2.6 on 2019-10-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_font_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='font_size',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
