# Generated by Django 2.2.6 on 2019-10-17 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_auto_20191016_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
    ]
