# Generated by Django 2.2.6 on 2019-10-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0005_programmer_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmer',
            name='age',
        ),
        migrations.AddField(
            model_name='programmer',
            name='birth_year',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
