# Generated by Django 2.2.6 on 2019-10-25 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
    ]
