# Generated by Django 3.0.6 on 2021-03-16 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0002_auto_20210315_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
