# Generated by Django 2.2.13 on 2020-06-15 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200615_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomChoices',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('polls.choice',),
        ),
    ]
