# Generated by Django 2.2.13 on 2020-06-15 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_customchoices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomChoices',
        ),
        migrations.CreateModel(
            name='CustomChoices',
            fields=[
                ('choice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.Choice')),
            ],
            options={
                'managed': False,
            },
            bases=('polls.choice',),
        ),
    ]
