# Generated by Django 2.2.13 on 2020-06-15 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200615_2128'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customchoices',
            table='choices_view',
        ),
    ]
