# Generated by Django 2.2.4 on 2019-09-04 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='tutorial_publish',
            new_name='tutorial_published',
        ),
    ]
