# Generated by Django 2.2.4 on 2019-09-04 15:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190904_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 4, 15, 10, 12, 418648, tzinfo=utc), verbose_name='date published'),
        ),
    ]
