# Generated by Django 2.2.6 on 2019-10-16 02:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('comment', models.TextField()),
                ('date_added', models.DateField(default=datetime.datetime(2019, 10, 16, 2, 59, 32, 239346, tzinfo=utc))),
            ],
        ),
    ]
