# Generated by Django 3.0.6 on 2020-06-20 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20200620_1826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicios',
            options={},
        ),
    ]
