# Generated by Django 3.0.6 on 2020-06-20 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_auto_20200620_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicios',
            options={'verbose_name_plural': 'Servicios'},
        ),
    ]
