# Generated by Django 2.2.6 on 2019-10-22 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='blog_posts',
        ),
    ]
