# Generated by Django 2.2.6 on 2019-10-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191022_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publicado',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created',
            new_name='creado',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='publish',
            new_name='publicado',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated',
        ),
        migrations.AddField(
            model_name='post',
            name='actualizado',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='estatus',
            field=models.CharField(choices=[('boceto', 'Boceto'), ('publicado', 'Publicado')], default='boceto', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='publicado'),
        ),
    ]
