# Generated by Django 2.2.6 on 2019-10-24 15:07

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191022_1806'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('objectos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('contenido', models.TextField()),
                ('creado', models.DateTimeField()),
                ('actualizado', models.DateTimeField()),
                ('activo', models.BooleanField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='blog.Post')),
            ],
            options={
                'ordering': ('creado',),
            },
        ),
    ]
