# Generated by Django 2.2.6 on 2019-10-24 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191024_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='contenido',
            new_name='comentario',
        ),
    ]
